{% set name = "rfc3987" %}
{% set version = "1.3.8" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d3c4d257a560d544e9826b38bc81db676890c79ab9d7ac92b39c7a253d5ca733" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports: "{{ name }}"

about:
  home: http://pypi.python.org/pypi/rfc3987
  license: GNU GPL3
  license_family: GPL3
  license_file: 'COPYING.txt'
  summary: Parsing and validation of URIs (RFC 3986) and IRIs (RFC 3987)
  description: This module provides regular expressions according to RFC 3986 and RFC 3987
  doc_url: ''
  dev_url: 'http://pypi.python.org/pypi/rfc3987'

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
