travis:
  secure:
    BINSTAR_TOKEN: 3JYyVTsXYdt6ioEc8mQ8/sZ7w3Zj3mC/oVhzKmIZb1fuRqJd+FkcsXzRhUF0Dd3IgThvcH/uQiGMvcjkrTI4whoQV5nh00tEFPNaNfocFD6+bACo7YVPUp8j/4j5w8/wEFTdThhV2Qdd9rPJpsICsWRqmrCIerH0AcE4R0DVrN3Q+qeAxgzEtbWU7WXriak7goCLxHVUhS0dRyH8oCi04/SEzuRI/OyiBov20Z53YnfpiH0enkp/HIfLL5F7gDMCtJJVTClG1JtFOvfu/F9DDUyw1vptxQ0FQLqHrW9Jm4swsWJ1bzAhCt6JED6s5cHeW/vz9By8O1PYSSG9Dzy87N9w5QcVJxdifh9rlzUJAKqfVNo8X7r5bYlB/rP2gqLxCPeCo+INyoNp0noRVlwGPqR9lpTq5ipBUYZc5zwD9L7PLQ4ByPAb9XGNQONhcQyHADusOxMHliAUArwyGNG61GjcvbccP5OP0qi28svrlx/iWzXqKs4EXqUG7RjPa2stMgdN4UWJ9BEmjfuIVYssQqMCvyfB3a8BRiYmguFdA2Gf/VKcId9RzCtYgN6+YjE/7m1/ZroT2mFF0YRpY7RXzX028Z0fPSfVdTlsD8wiKk5aMeD48yrx000MBCeCMJEOqGJY5dABO80fDo8UCQOyHgZKR+cCX6JEcjmvEfp4kdY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
