travis:
  secure:
    BINSTAR_TOKEN: M6g3wW7oGfweoBA6vprsySU7CafvEJzq97e72OLQflYS3fdYg5eFfEbdxItcEWdbvsWlNX66Gc2BY93ncU5+2lONm9hHaGckt2glbv/eOWVZdEizcmUzDsRcx9pT2LyEHIzL6uNYCZ7uoKGXkfgv3JyEtFBWrzu07Jdz8WrjWWUREJgcfetBITz12la+3PJKuHk8ijIMJmgmZezc4+R3wDGLodjNY1BmB6cZ9ej2WM9YC8teskPr8GE+tl45Sw2c+wVYkAArwzpjoLgoSqty3ZwLCu8pnfAcMOyxztnvGDFMEDc9ZnG3cDinTG3Ra6He2+ecmD+ayeVa2ZXF0prhFKhJRd07cC6J4FPQdVJW0wEpk9UaBr8S4K52b2Nb8v1B148vHyCz2YKVkdM47xuxGcTr7/OB/Rn7ML8c6araKFnyIHu5qtmVV0QyWh559A3yqn+tLaZbbxvGehGcquTUrfoy0COzM+UO7vFVzqH+mxTuIGZV35olVWSUaxX7AxZ3Z6pECel6LtnZfjcg73sgwP3J7TwNxuhIAeB5b5WbSRUk/JGyEvaNZOxv3UbdzHJtJ48zbChqCgjjhTmR3VAcijpnFsfjJWbOqvNGw5H+rq3Rswqe01BMdZPcacdR0wkUn5jiKH0rZqPOiiLT9aAIK8p+pUwPg2PmytQrbnajn8g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
